name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy
      cancel-in-progress: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            docs/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Root Node Modules
        run: npm install

      - name: Webpack Dev Build
        id: webpack-dev
        run: node webpack.js development
        timeout-minutes: 10

      - name: Webpack Dist Build
        id: webpack-dist
        run: node webpack.js production
        timeout-minutes: 10

      - name: Install Docs Dependencies
        run: |
          cd docs
          npm install

      - name: Generate SDK Documentation
        run: |
          cd docs
          npm run generate

      - name: Build Docusaurus Site
        timeout-minutes: 30
        run: |
          cd docs
          npm run build

      - name: Commit Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          if [[ -n "$(git status --porcelain)" ]]; then
            git add ./dist ./dev ./docs
            git commit -m "Deployed on $(date) [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi

      - name: Upload Development to S3
        uses: tpaschalis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          FILE: ./dev/geoflo-sdk.js
          AWS_REGION: "us-east-1"
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}/sdk/
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}

      - name: Upload CSS to S3
        uses: tpaschalis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          FILE: ./dist/geoflo-sdk.css
          AWS_REGION: "us-east-1"
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}/sdk/
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.AWS_CFDIST }}
          PATHS: "/*"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
