name: Release
on:
  release:
    types:
      - created
permissions:
  contents: write
  packages: write
jobs:
  release:
    runs-on: ubuntu-latest
    concurrency:
      group: release
      cancel-in-progress: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - name: Install Dependencies
        run: npm ci
      - name: Upload Production to S3
        uses: tpaschalis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          FILE: ./dist/geoflo-sdk.min.js
          AWS_REGION: "us-east-1"
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}/sdk/
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
      - name: Upload CSS to S3
        uses: tpaschalis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          FILE: ./dist/geoflo-sdk.css
          AWS_REGION: "us-east-1"
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}/sdk/
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.AWS_CFDIST }}
          PATHS: "/*"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
      - name: Publish to GitHub Packages
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
